In [5]:
import gymnasium as gym

In [6]:
env = gym.make("CarRacing-v2")

In [10]:
obs, _ = env.reset()
print(obs)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [35]:
n_obs = np.moveaxis(obs, -1, 0)

In [39]:
print(n_obs.shape, obs.shape)

(3, 210, 160) (210, 160, 3)


In [36]:
print(n_obs)

[[[239 105 195 ... 244 161 130]
  [216 206 248 ... 190 132 251]
  [223 148 192 ... 171  18 222]
  ...
  [214 141 227 ... 215 137 148]
  [ 42  63 115 ... 239 173  33]
  [178 161 118 ... 142 239 168]]

 [[228 171 186 ... 113 116  62]
  [ 46  33 186 ... 150  64  15]
  [ 33 184   2 ... 234 199 244]
  ...
  [171  58  73 ... 172 215 175]
  [ 89 242 222 ...  68 152 157]
  [ 53 135 154 ...  35 127 104]]

 [[ 45 115 242 ...  18 128 215]
  [119 177   7 ... 229 173 124]
  [214  78 176 ... 143 241  15]
  ...
  [ 69  65 129 ...  89  56  72]
  [178 100 110 ... 155  80 144]
  [144 187 199 ... 105  47  20]]]


In [32]:
print(obs)

[[[239 228  45]
  [105 171 115]
  [195 186 242]
  ...
  [244 113  18]
  [161 116 128]
  [130  62 215]]

 [[216  46 119]
  [206  33 177]
  [248 186   7]
  ...
  [190 150 229]
  [132  64 173]
  [251  15 124]]

 [[223  33 214]
  [148 184  78]
  [192   2 176]
  ...
  [171 234 143]
  [ 18 199 241]
  [222 244  15]]

 ...

 [[214 171  69]
  [141  58  65]
  [227  73 129]
  ...
  [215 172  89]
  [137 215  56]
  [148 175  72]]

 [[ 42  89 178]
  [ 63 242 100]
  [115 222 110]
  ...
  [239  68 155]
  [173 152  80]
  [ 33 157 144]]

 [[178  53 144]
  [161 135 187]
  [118 154 199]
  ...
  [142  35 105]
  [239 127  47]
  [168 104  20]]]
